version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: fraudguard-db
    environment:
      POSTGRES_DB: fraudguard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fraudguard-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: fraudguard-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fraudguard-network

  # Spring Boot Backend
  backend:
    build: ./backend
    container_name: fraudguard-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=fraudguard
      - DB_USER=admin
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - fraudguard-network

volumes:
  postgres_data:
  redis_data:

networks:
  fraudguard-network:
    driver: bridge
