server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:fraudguard
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  h2:
    console:
      enabled: true

logging:
  level:
    com.fraudguard: DEBUG
